- name: configure frontend and install nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: installed

  - name: enable and start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

  - name: remove default content in html folder
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent

  - name: create html directory
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: directory

  - name: Download the frontend content
    ansible.builtin.get_url:
     url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
     dest: /tmp/frontend.zip

  - name: unzip the frontend
    ansible.builtin.unarchive:
     src: /tmp/frontend.zip
     dest: /usr/share/nginx/html
     remote_src: yes