- name: configure frontend and install nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: installed

  - name: enable and start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes

  - name: remove default content in html folder
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent